FROM python:3.12.4-alpine3.20



RUN apk add --no-cache curl

WORKDIR /app
COPY . /app/
# first copy the dependencies only


# Upgrade pip & setuptools
RUN pip install --upgrade pip setuptools wheel

COPY flask/requirements.txt .

RUN pip install  -r requirements.txt

# Install the dependencies 


# now copy the app code
# build time by using the cache if no new dependencies are added

CMD ["gunicorn","--bind","0.0.0.0:8080","app:app"]