name: CI/CD for Dockerized Flask App

on :
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional: log in to DockerHub if you need private images
      # - name: Log in to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and start services
        run: docker compose -f docker-compose.yaml up -d --build

      - name: Run tests (inside a service container)
        run: docker compose exec -T flask pytest
        # 👆 replace `flask` with the service name from your docker-compose.yaml

      - name: Stop and remove containers
        if: always()
        run: docker compose -f docker-compose.yaml down -v

  build-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./flask/Dockerfile.dev
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest
        source: |
          docker-compose.yaml
        target: flask
    - name: Image digest
      run: echo ${{ steps.build-and-push.outputs.digest }}
      

